# Generated by Django 5.1.4 on 2024-12-14 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('revision', models.CharField(blank=True, max_length=100, null=True)),
                ('is_modular', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FixedPlatform',
            fields=[
                ('platform_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='configurator.platform')),
                ('port_index', models.IntegerField(default=0)),
                ('port_name_template', models.TextField()),
            ],
            bases=('configurator.platform',),
        ),
        migrations.CreateModel(
            name='ModularPlatform',
            fields=[
                ('platform_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='configurator.platform')),
                ('num_slots', models.IntegerField(default=0)),
                ('slot_index', models.IntegerField(default=0)),
            ],
            bases=('configurator.platform',),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('revision', models.CharField(blank=True, max_length=100, null=True)),
                ('is_supervisor', models.BooleanField(default=False)),
                ('port_index', models.IntegerField(default=0)),
                ('port_name_template', models.TextField()),
                ('speed_prefix_map', models.JSONField(blank=True, default=dict)),
                ('supported_platforms', models.ManyToManyField(related_name='supported_cards', to='configurator.platform')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('allowed_platforms', models.ManyToManyField(related_name='roles', to='configurator.platform')),
            ],
        ),
        migrations.CreateModel(
            name='SlotInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.IntegerField(unique=True)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configurator.card')),
                ('modular_platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='configurator.modularplatform')),
            ],
        ),
        migrations.AddField(
            model_name='modularplatform',
            name='supported_cards',
            field=models.ManyToManyField(blank=True, related_name='supported_by_platforms', to='configurator.card'),
        ),
    ]
