# Generated by Django 5.1.4 on 2024-12-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0003_card_num_ports_fixedplatform_num_ports'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedplatform',
            name='speed_prefix_map',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
