# Generated by Django 5.1.4 on 2024-12-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0004_fixedplatform_speed_prefix_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='port_index',
        ),
        migrations.AddField(
            model_name='modularplatform',
            name='port_index',
            field=models.IntegerField(default=0),
        ),
    ]
